const LANGUAGE_OPTIONS = [
  ['ab', 'Abkhaz'],
  ['aa', 'Afar'],
  ['af', 'Afrikaans'],
  ['ak', 'Akan'],
  ['sq', 'Albanian'],
  ['am', 'Amharic'],
  ['ar', 'Arabic'],
  ['an', 'Aragonese'],
  ['hy', 'Armenian'],
  ['as', 'Assamese'],
  ['av', 'Avaric'],
  ['ae', 'Avestan'],
  ['ay', 'Aymara'],
  ['az', 'Azerbaijani'],
  ['bm', 'Bambara'],
  ['ba', 'Bashkir'],
  ['eu', 'Basque'],
  ['be', 'Belarusian'],
  ['bn', 'Bengali'],
  ['bho', 'Bhojpuri'],
  ['bi', 'Bislama'],
  ['bs', 'Bosnian'],
  ['br', 'Breton'],
  ['bg', 'Bulgarian'],
  ['my', 'Burmese'],
  ['ca', 'Catalan'],
  ['ceb', 'Cebuano'],
  ['ch', 'Chamorro'],
  ['ce', 'Chechen'],
  ['chr', 'Cherokee'],
  ['ny', 'Chichewa'],
  ['zh-Hans', 'Chinese Simplified'],
  ['zh-Hant', 'Chinese Traditional'],
  ['cv', 'Chuvash'],
  ['kw', 'Cornish'],
  ['co', 'Corsican'],
  ['cr', 'Cree'],
  ['hr', 'Croatian'],
  ['cs', 'Czech'],
  ['da', 'Danish'],
  ['dv', 'Divehi'],
  ['doi', 'Dogri'],
  ['nl', 'Dutch'],
  ['dz', 'Dzongkha'],
  ['en', 'English'],
  ['eo', 'Esperanto'],
  ['et', 'Estonian'],
  ['ee', 'Ewe'],
  ['fo', 'Faroese'],
  ['fj', 'Fijian'],
  ['fil', 'Filipino'],
  ['fi', 'Finnish'],
  ['fr', 'French'],
  ['ff', 'Fulah'],
  ['gl', 'Galician'],
  ['lg', 'Ganda'],
  ['ka', 'Georgian'],
  ['de', 'German'],
  ['el', 'Greek'],
  ['gn', 'Guarani'],
  ['gu', 'Gujarati'],
  ['ht', 'Haitian Creole'],
  ['ha', 'Hausa'],
  ['haw', 'Hawaiian'],
  ['he', 'Hebrew'],
  ['hi', 'Hindi'],
  ['hmn', 'Hmong'],
  ['hu', 'Hungarian'],
  ['is', 'Icelandic'],
  ['ig', 'Igbo'],
  ['ilo', 'Ilocano'],
  ['id', 'Indonesian'],
  ['ia', 'Interlingua'],
  ['ie', 'Interlingue'],
  ['iu', 'Inuktitut'],
  ['ik', 'Inupiaq'],
  ['ga', 'Irish'],
  ['it', 'Italian'],
  ['ja', 'Japanese'],
  ['jv', 'Javanese'],
  ['kl', 'Kalaallisut'],
  ['kn', 'Kannada'],
  ['kr', 'Kanuri'],
  ['ks', 'Kashmiri'],
  ['kk', 'Kazakh'],
  ['km', 'Khmer'],
  ['rw', 'Kinyarwanda'],
  ['kv', 'Komi'],
  ['kg', 'Kongo'],
  ['kok', 'Konkani'],
  ['ko', 'Korean'],
  ['ku', 'Kurdish Kurmanji'],
  ['ckb', 'Kurdish Sorani'],
  ['kj', 'Kuanyama'],
  ['ky', 'Kyrgyz'],
  ['lo', 'Lao'],
  ['la', 'Latin'],
  ['lv', 'Latvian'],
  ['li', 'Limburgish'],
  ['ln', 'Lingala'],
  ['lt', 'Lithuanian'],
  ['lu', 'Luba-Katanga'],
  ['lb', 'Luxembourgish'],
  ['mk', 'Macedonian'],
  ['mai', 'Maithili'],
  ['mg', 'Malagasy'],
  ['ms', 'Malay'],
  ['ml', 'Malayalam'],
  ['mt', 'Maltese'],
  ['gv', 'Manx'],
  ['mi', 'Maori'],
  ['mr', 'Marathi'],
  ['mh', 'Marshallese'],
  ['mni', 'Meiteilon'],
  ['lus', 'Mizo'],
  ['mn', 'Mongolian'],
  ['na', 'Nauru'],
  ['nv', 'Navajo'],
  ['nd', 'North Ndebele'],
  ['nr', 'South Ndebele'],
  ['ne', 'Nepali'],
  ['se', 'Northern Sami'],
  ['no', 'Norwegian'],
  ['nb', 'Norwegian Bokmal'],
  ['nn', 'Norwegian Nynorsk'],
  ['nso', 'Northern Sotho'],
  ['oc', 'Occitan'],
  ['oj', 'Ojibwe'],
  ['or', 'Odia'],
  ['om', 'Oromo'],
  ['os', 'Ossetian'],
  ['pi', 'Pali'],
  ['ps', 'Pashto'],
  ['fa', 'Persian'],
  ['pl', 'Polish'],
  ['pt', 'Portuguese'],
  ['pt-BR', 'Portuguese Brazil'],
  ['pa', 'Punjabi'],
  ['qu', 'Quechua'],
  ['ro', 'Romanian'],
  ['rm', 'Romansh'],
  ['rn', 'Rundi'],
  ['ru', 'Russian'],
  ['sm', 'Samoan'],
  ['sg', 'Sango'],
  ['sa', 'Sanskrit'],
  ['sc', 'Sardinian'],
  ['gd', 'Scots Gaelic'],
  ['sr-Cyrl', 'Serbian Cyrillic'],
  ['sr-Latn', 'Serbian Latin'],
  ['st', 'Sesotho'],
  ['sn', 'Shona'],
  ['sd', 'Sindhi'],
  ['si', 'Sinhala'],
  ['sk', 'Slovak'],
  ['sl', 'Slovenian'],
  ['so', 'Somali'],
  ['es', 'Spanish'],
  ['su', 'Sundanese'],
  ['sw', 'Swahili'],
  ['ss', 'Swati'],
  ['sv', 'Swedish'],
  ['tl', 'Tagalog'],
  ['ty', 'Tahitian'],
  ['tg', 'Tajik'],
  ['ta', 'Tamil'],
  ['tt', 'Tatar'],
  ['te', 'Telugu'],
  ['th', 'Thai'],
  ['bo', 'Tibetan'],
  ['ti', 'Tigrinya'],
  ['to', 'Tongan'],
  ['ts', 'Tsonga'],
  ['tn', 'Tswana'],
  ['tr', 'Turkish'],
  ['tk', 'Turkmen'],
  ['tw', 'Twi'],
  ['ug', 'Uyghur'],
  ['uk', 'Ukrainian'],
  ['ur', 'Urdu'],
  ['uz', 'Uzbek'],
  ['ve', 'Venda'],
  ['vi', 'Vietnamese'],
  ['vo', 'Volapuk'],
  ['wa', 'Walloon'],
  ['cy', 'Welsh'],
  ['fy', 'Western Frisian'],
  ['wo', 'Wolof'],
  ['xh', 'Xhosa'],
  ['yi', 'Yiddish'],
  ['yo', 'Yoruba'],
  ['za', 'Zhuang'],
  ['zu', 'Zulu'],
]

export const TRANSLATION_LANGUAGES = LANGUAGE_OPTIONS.map(([code, name]) => ({
  code,
  name,
  value: `${name} (${code})`,
}))

export const DEFAULT_TRANSLATION_LANGUAGE = 'English (en)'
