package com.moonback.pilgrimage.batch.ingest.model;

public enum IngestStatus {
	DISCOVERED,
	PARSED,
	TMDB_MATCHED,
	TMDB_NOT_FOUND,
	TMDB_AMBIGUOUS,
	NON_DOMESTIC,
	GEOCODE_NOT_FOUND,
	GEOCODE_AMBIGUOUS,
	SCENE_SAVED,
	IMAGE_PENDING,
	IMAGE_DOWNLOADED,
	IMAGE_CONVERTED,
	IMAGE_UPLOADED,
	COMPLETED,
	FAILED
}
